name: Javadoc workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repo
          uses: actions/checkout@v2

        - name: Set up the Java JDK
          uses: actions/setup-java@v2
          with:
            java-version: '16'
            distribution: 'adopt'

        - name: Build docs with Maven
          run: mvn javadoc:javadoc

        - name: Copy to Documentation Website Location
          run: |
            rm -rf docs
            cp -rf target/site/apidocs/. docs

#        - name: pull
#          run: git pull

        - name: fetch from master
          run: git fetch

        - name: check for changes
          run: git status

        - name: Commit documentation changes
          run: |
              git config --global user.name 'Michael Grygiel'
              git config --global user.email 'gg-mike@users.noreply.github.com'
              git add docs
              git commit -m "add javadoc"

        - name: Push changes
          run: git push origin/github-actions-javadoc
